sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t clydotron/docker-react -f Dockerfile.dev .

  script:
    - docker run -e CI=true clydotron/docker-react npm run test